select 
t.TABLE_SCHEMA, t.TABLE_NAME, t.TABLE_TYPE, 
Total_Rows= SUM(st.row_count),
c.COLUMN_NAME, c.ORDINAL_POSITION, c.DATA_TYPE, c.CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.TABLES t

INNER JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
INNER JOIN sys.dm_db_partition_stats st ON t.TABLE_NAME = object_name(st.object_id) AND (st.index_id < 2)

GROUP BY t.TABLE_SCHEMA, t.TABLE_NAME, t.TABLE_TYPE,
c.COLUMN_NAME, c.ORDINAL_POSITION, c.DATA_TYPE, c.CHARACTER_MAXIMUM_LENGTH
ORDER BY TABLE_NAME, c.ORDINAL_POSITION

